id: PC78343A6
initial_creation_type: input
source_metadata:
  title: Apang Tertön Series
  language: bo
  description: 'Texts by and about Apang Tertön (a paṃ gter ston) alias Pawo Chöying
    Dorje (dpa'' bo chos dbyings rdo rje, 1895–1945):'
  volume:
    4195af13022048d6b3bd1994984deeec:
      title: A Prayer for Auspiciousness
      parent: Auspiciousness
    fc74944f3a4b41a6b513f800afd49b17:
      title: A Prayer to Chöying Dorje
      parent: Prayers
    da3ccd4e975c4713b7e0cb817d4a7edd:
      title: A Prayer to Mañjuśrī
      parent: Prayers
    cac1a71178e24a28961a40f2855de0da:
      title: A Prayer to Yumka Tsogyal
      parent: Prayers
    6072c40e326b43f6b04fcf11401d4203:
      title: A Short Prayer to Chöying Dorje
      parent: Prayers
    5aceb3daf125486bb24e99e4e9205099:
      title: Daily Practice of Vajrakīla
      parent: Sādhanas
created_at: '2022-02-28T22:39:48.652077'
last_modified_at: '2022-02-28T22:39:48.652080'
